[GeneralConfig]
URL = "profcast.studieren-ohne-grenzen.org/" # This is the URL that the download links relate to (without method).
Method = "https" # http or https
Title = "SOG Profcast"
Description = "Profs reden über Musik und mehr"
Link = "profcast.studieren-ohne-grenzen.org/" # This is the URL that you get to when you click on (also without method).
ImageTitle = "SOG Profcast"
Copyright = "Studieren Ohne Grenzen Aachen"
Language = "de-de"
ITunesAuthor = "Studieren Ohne Grenzen Aachen"
ITunesType = "episodic"
ITunesAuthorName = "Studieren Ohne Grenzen Aachen"
ITunesAuthorEmail = "aachen@studieren-ohne-grenzen.org"
ITunesExplicit = "no" # One of yes or no
# Make sure this category actually exists: https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
ITunesCategory = "Music"
ITunesSubcategory = "Music Interviews"

# Below is the list of episodes.

[[Episode]]
EpisodeTitle = "Folge 1: Prof. Dr. Klaus Reicherter"
EpisodeDescription = """
Prof. Dr. Reicherter ist Professor für Neotektonik und Georisiken an der RWTH Aachen.
<br>
Playlist auf Spotify: <a href="https://open.spotify.com/playlist/3wa6gV2alwz98Geya5Suxy">https://open.spotify.com/playlist/3wa6gV2alwz98Geya5Suxy</a>
<ul>
<li>Stairway to Heaven von Led Zeppelin</li>
<li>Lazarus von Porcupine Tree</li>
<li>Miss Murder von AFI</li>
<li>November Rain von Guns N' Roses</li>
<li>Bohemian Rhapsody von Queen</li>
<li>Highway to Hell von AC/DC</li>
</ul>
"""
Audio = "001.mp3" # In static/download/audio
PubDate = "31 Aug 2020"
ITunesSeason = "1"
ITunesEpisode = "1"
