[GeneralConfig]
URL = "podcast-aachen.others-production.esf-international.org/" # This is the URL that the download links relate to (without method).
Method = "https" # http or https
Title = "Aachener Podcast (Test)"
Description = "Hier entsteht der Aachener Podcast"
Link = "podcast-aachen.others-production.esf-international.org/" # This is the URL that you get to when you click on (also without method).
ImageTitle = "SOG Podcast"
Copyright = "Studieren Ohne Grenzen Aachen"
Language = "de-de"
ITunesAuthor = "Studieren Ohne Grenzen Aachen"
ITunesType = "episodic"
ITunesAuthorName = ""
ITunesAuthorEmail = ""
ITunesExplicit = "no" # One of yes or no
# Make sure this category actually exists: https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
ITunesCategory = "Music"
ITunesSubcategory = "Music Interviews"

[[Episode]]
EpisodeTitle = "Eine Test-Folge"
EpisodeDescription = "Bitte probiert das nicht zu Hause"
Audio = "001.mp3" # In static/download/audio
PubDate = "19 Apr 2020"
ITunesSeason = "1"
ITunesEpisode = "1"
