[GeneralConfig]
URL = "profcast.studieren-ohne-grenzen.org/" # This is the URL that the download links relate to (without method).
Method = "https" # http or https
Title = "SOG Profcast"
Description = "Profs reden über Musik und mehr"
Link = "profcast.studieren-ohne-grenzen.org/" # This is the URL that you get to when you click on (also without method).
ImageTitle = "SOG Profcast"
Copyright = "Studieren Ohne Grenzen Aachen"
Language = "de-de"
ITunesAuthor = "Studieren Ohne Grenzen Aachen"
ITunesType = "episodic"
ITunesAuthorName = ""
ITunesAuthorEmail = ""
ITunesExplicit = "no" # One of yes or no
# Make sure this category actually exists: https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
ITunesCategory = "Music"
ITunesSubcategory = "Music Interviews"

# Below is the list of episodes.

# [[Episode]]
# EpisodeTitle = "Eine Test-Folge"
# EpisodeDescription = """
# Das ist ein Test einer Multi-Line Description.
# <br>
# Klappt das so, wie es hier ist?
# """
# Audio = "001.mp3" # In static/download/audio
# PubDate = "19 Apr 2020"
# ITunesSeason = "1"
# ITunesEpisode = "1"
