[GeneralConfig]
URL = "localhost:8080" # This is the URL that the download links relate to.
Method = "http" # http or https
Title = "TestPodcast"
Description = "Nix"
Link = "Nirgendwo" # This is the URL that you get to when you click on.
ImageTitle = "SOG Podcast"
Copyright = "Niemand"
Language = "de-de"
ITunesAuthor = ""
ITunesType = "episodic"
ITunesAuthorName = ""
ITunesAuthorEmail = ""
ITunesExplicit = "no" # One of yes or no
# Make sure this category actually exists: https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
ITunesCategory = "Society &amp; Culture"
ITunesSubcategory = "Philosophy"

[[Episode]]
EpisodeTitle = "Eine Test-Folge"
EpisodeDescription = "Bitte probiert das nicht zu Hause"
Audio = "001.mp3" # In static/download/audio
PubDate = "19 Apr 2020"
ITunesSeason = "1"
ITunesEpisode = "1"
